security:
  oauth2:
    client:
      client-id: 386756508431565
      client-secret: 5362faf1c99027066bf8c260e7991d06
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

server:
  port: 8091

#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

#debug: true